/**
 * Types-only stand-in for the private `@hey/db` package: the enum unions the
 * scoring package imports. Generated by the export script from the schema;
 * do not edit here.
 */

export const PROJECT_KINDS = [
  'UTILITY',
  'MEME',
  'HYBRID',
  'INFRASTRUCTURE',
  'RWA',
  'APPLICATION',
  'OTHER',
] as const;

export type ProjectKind = (typeof PROJECT_KINDS)[number];

export const ACTIVITY_STATUSES = [
  'SHIPPING',
  'ACTIVE',
  'QUIET',
  'DORMANT',
  'RESUMED',
  'UNKNOWN',
] as const;

export type ActivityStatus = (typeof ACTIVITY_STATUSES)[number];

export const SHIP_EVENT_TYPES = [
  'PRODUCT_LAUNCH',
  'FEATURE_RELEASE',
  'APP_RELEASE',
  'GITHUB_RELEASE',
  'CODE_ACTIVITY',
  'CONTRACT_DEPLOY',
  'CONTRACT_UPGRADE',
  /** A contract the project's own deployer put up after the launch (2026-09-12): building, unlike the launch deploy. */
  'CONTRACT_DEPLOY_FOLLOWUP',
  'INTEGRATION',
  'DOCS_UPDATE',
  'ROADMAP_MILESTONE',
  'API_RELEASE',
  'SDK_RELEASE',
  'DESIGN_RELEASE',
  'DEMO_RELEASE',
  'COMMUNITY_TOOL',
  'GAME_RELEASE',
  'CREATIVE_DROP',
  'COMMUNITY_EVENT',
  'FOUNDER_BUILD_UPDATE',
  'ANNOUNCEMENT',
  'OTHER',
] as const;

export type ShipEventType = (typeof SHIP_EVENT_TYPES)[number];

export const VERIFICATION_STATUSES = [
  'SELF_REPORTED',
  'SOURCE_LINKED',
  'PUBLICLY_VERIFIED',
  'ADMIN_VERIFIED',
  'DISPUTED',
  'RETRACTED',
] as const;

export type VerificationStatus = (typeof VERIFICATION_STATUSES)[number];

export const SHIP_SOURCE_KINDS = [
  'GITHUB',
  'WEBSITE',
  'RSS',
  'CONTRACT',
  'LAUNCHPAD',
  'BUILDER_SUBMISSION',
  'ADMIN',
  'COMMUNITY',
  'OTHER',
] as const;

export type ShipSourceKind = (typeof SHIP_SOURCE_KINDS)[number];

export const SOURCE_TYPES = [
  'WEBSITE',
  'DOCS',
  'CHANGELOG',
  'RSS',
  'GITHUB_REPO',
  'GITHUB_ORG',
  'BLOCKSCOUT',
  'CONTRACT',
  'LAUNCHPAD',
  'X',
  /**
   * The builder's own X account, when they gave one on the submission form
   * (2026-09-05). Deliberately not `X`: a person's account is not the
   * project's, and the card's "official X" reads `X` — folding the two would
   * print a personal handle as the project's own.
   */
  'BUILDER_X',
  'FARCASTER',
  'TELEGRAM',
  'DISCORD',
  'OTHER',
] as const;

export type SourceType = (typeof SOURCE_TYPES)[number];

export const MODERATION_STATUSES = [
  'PENDING',
  'APPROVED',
  'REJECTED',
  'SPAM',
  'NEEDS_INFO',
] as const;

export type ModerationStatus = (typeof MODERATION_STATUSES)[number];

export const MODERATION_REASONS = [
  'SPAM',
  'PHISHING',
  'MALWARE',
  'DUPLICATE_PROJECT',
  'IMPERSONATION',
  'FALSE_CLAIM',
  'DISPUTED_EVIDENCE',
  'CONFLICTING_CONTRACT',
  'INAPPROPRIATE',
  'OTHER',
] as const;

export type ModerationReason = (typeof MODERATION_REASONS)[number];

export const MODERATION_FLAG_STATUSES = ['OPEN', 'RESOLVED', 'DISMISSED'] as const;

export type ModerationFlagStatus = (typeof MODERATION_FLAG_STATUSES)[number];

export const CLAIM_STATUSES = ['UNCLAIMED', 'PENDING', 'VERIFIED', 'REJECTED'] as const;

export type ClaimStatus = (typeof CLAIM_STATUSES)[number];

export const CLAIM_METHODS = ['GITHUB', 'DNS_TXT', 'WEBSITE_FILE', 'ONCHAIN_SIGNATURE'] as const;

export type ClaimMethod = (typeof CLAIM_METHODS)[number];

export const USER_ROLES = ['USER', 'BUILDER', 'RESEARCHER', 'MODERATOR', 'ADMIN'] as const;

export type UserRole = (typeof USER_ROLES)[number];

export const REFRESH_TIERS = ['HOT', 'WARM', 'COOL', 'COLD'] as const;

export type RefreshTier = (typeof REFRESH_TIERS)[number];

export const JOB_STATUSES = ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'] as const;

export type JobStatus = (typeof JOB_STATUSES)[number];

export const TOKEN_VERIFICATIONS = ['VERIFIED', 'UNVERIFIED', 'MISMATCH'] as const;

export type TokenVerification = (typeof TOKEN_VERIFICATIONS)[number];

export const TOKEN_MARKET_STATUSES = [
  'ACTIVE_MARKET',
  'LOW_LIQUIDITY',
  'NO_LIQUIDITY',
  'TRADING_INACTIVE',
  'LIQUIDITY_REMOVED',
  'MARKET_ABANDONED',
  'INSUFFICIENT_DATA',
] as const;

export type TokenMarketStatus = (typeof TOKEN_MARKET_STATUSES)[number];
